heat_template_version: 2013-05-23

description: Simple template to deploy a single compute instance

parameters:
  key_name:
    type: string
    label: Key Name
    default: default
    description: Name of key-pair to be used for compute instance
  image:
    type: string
    label: Image Name
    default: Ubuntu-Server-14.04
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Type
    default: standard.small
    description: Type of instance (flavor) to be used
  network:
    type: string
    label: Network Name
    default: default-network
    description: Newtork name to assocaite server with

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: server1_port }
  server1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }
