heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  # pool_id:
  #   type: string
  #   description: Pool to contact
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
  subnet_id:
    type: string
    description: Network name
resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      networks:
       - network: {get_param: subnet_id}
      metadata: {get_param: metadata}
      user_data: {get_param: user_data}
      user_data_format: RAW
  # member:
  #   type: OS::Neutron::PoolMember
  #   properties:
  #     pool_id: {get_param: pool_id}
  #     address: {get_attr: [server, first_address]}
  #     protocol_port: 80
