heat_template_version: 2013-05-23

description: >
  Simple template to deploy a bastion host with the CLI tools
  via the Horizon UI. This assumes that there is still quota
  for additional Floating IP address allocation, as this template
  will allocate a new Floating IP for this VM deployment

parameters:
  key_name:
    type: string
    label: Key Name
    default: default
    description: Name of key-pair to be used for compute instance
  image:
    type: string
    label: Image Name
    default: Ubuntu-Server-14.04
    description: Image to be used for compute instance
  instance_type:
    type: string
    label: Instance Type
    default: standard.small
    description: Type of instance (flavor) to be used
  network:
    type: string
    label: Network Name
    default: default-network
    description: Newtork name to assocaite server with
  public_net:
    type: string
    label: Public Network
    default: Ext-Net
    description: Newtork name for Floating IPs
  tenant_name:
    type: string
    label: Tenant Project Name
    constraints:
      - allowed_pattern: "[a-z]+[a-zA-Z0-9-]*"
        description: User name must start with an uppercase character
  user_name:
    type: string
    label: Tenant User Name
    constraints:
      - allowed_pattern: "[a-z]+[a-zA-Z0-9]*"
        description: User name must start with an uppercase character

resources:
  cloud_tools:
    type: OS::Nova::Server
    properties:
      name: cloud-tools
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: instance_type }
      networks:
        - port: { get_resource: server_1_port }
      admin_user: ubuntu
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            #
            # Setup an Ubuntu VM with the OpenStack Cloud Tools

            # Determine the local cloud user, most likely the
            # Only user in the /home diretory, and for an
            # example, set the local password as well.
            user=`ls /home | head -1`
            passwd $user <<EOF
            DiffiCultPassWordToRemember
            DiffiCultPassWordToRemember
            EOF

            chsh -s /bin/bash $user

            apt-get update -y
            clients='nova
            neutron
            glance
            heat
            cinder
            designate
            openstack
            keystone'

            for n in ${clients}
            do
             apt-get install python-${n}client  -y
            done

            apt-get install python-pip -y
            pip install --upgrade python-swiftclient
            pip install --upgrade python-monascaclient
            easy_install --upgrade requests[security]


            echo "`ip addr show eth0 | awk '/ inet / {print $2}' | cut -d\/ -f1`  `hostname`" >> /etc/hosts

            cat > /home/$user/openrc.sh <<EOF
            #!/bin/bash
            export OS_AUTH_URL=https://chrcnc-api.os.cloud.twc.net:5000/v2.0
            export OS_TENANT_NAME="$tenant_name"
            export OS_USERNAME="$user_name"
            export OS_REGION_NAME="NCE"

            echo "Please enter your OpenStack Password: "
            read -sr OS_PASSWORD_INPUT
            export OS_PASSWORD=\$OS_PASSWORD_INPUT

            export PS1='[\u@\h \W(nce)]\$ '
            EOF

            cat > /home/$user/w.sh <<EOF
            #!/bin/bash

            export OS_AUTH_URL=https://dnvrco-api.os.cloud.twc.net:5000/v2.0
            export OS_REGION_NAME="NCW"
            export PS1='[\u@\h \W(ncw)]\$ '
            EOF

            cat > /home/$user/e.sh <<EOF
            #!/bin/bash

            export OS_AUTH_URL=https://chrcnc-api.os.cloud.twc.net:5000/v2.0
            export OS_REGION_NAME="NCE"
            export PS1='[\u@\h \W(nce)]\$ '
            EOF


          params:
            $tenant_name: { get_param: tenant_name}
            $user_name: { get_param: user_name }

  server_1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: network }

  server_1_floating_ip_id:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
  server_1_floating_ip_association:
    type: OS::Neutron::FloatingIPAssociation
    properties:
      floatingip_id: { get_resource: server_1_floating_ip_id }
      port_id: { get_resource: server_1_port }

outputs:
  server_floating_ip:
    description: The Floating IP address of the deployed server
    value: { get_attr: [server_1_floating_ip_id, floating_ip_address] }
  server_info:
    description: values of server
    value: { get_attr: [cloud_tools, show]}


